//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hetedik
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tick
    {
        public int Tick_id { get; set; }
        public string Index { get; set; }
        public System.DateTime TradingDay { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> Volume { get; set; }
    }
}
